/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HeartScoreLazyImport = createFileRoute('/heart-score')()
const AcuteOneLazyImport = createFileRoute('/acute-one')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HeartScoreLazyRoute = HeartScoreLazyImport.update({
  id: '/heart-score',
  path: '/heart-score',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heart-score.lazy').then((d) => d.Route))

const AcuteOneLazyRoute = AcuteOneLazyImport.update({
  id: '/acute-one',
  path: '/acute-one',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/acute-one.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/acute-one': {
      id: '/acute-one'
      path: '/acute-one'
      fullPath: '/acute-one'
      preLoaderRoute: typeof AcuteOneLazyImport
      parentRoute: typeof rootRoute
    }
    '/heart-score': {
      id: '/heart-score'
      path: '/heart-score'
      fullPath: '/heart-score'
      preLoaderRoute: typeof HeartScoreLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/acute-one': typeof AcuteOneLazyRoute
  '/heart-score': typeof HeartScoreLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/acute-one': typeof AcuteOneLazyRoute
  '/heart-score': typeof HeartScoreLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/acute-one': typeof AcuteOneLazyRoute
  '/heart-score': typeof HeartScoreLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acute-one' | '/heart-score'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acute-one' | '/heart-score'
  id: '__root__' | '/' | '/acute-one' | '/heart-score'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AcuteOneLazyRoute: typeof AcuteOneLazyRoute
  HeartScoreLazyRoute: typeof HeartScoreLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AcuteOneLazyRoute: AcuteOneLazyRoute,
  HeartScoreLazyRoute: HeartScoreLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/acute-one",
        "/heart-score"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/acute-one": {
      "filePath": "acute-one.lazy.jsx"
    },
    "/heart-score": {
      "filePath": "heart-score.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
