name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed so the GH_TOKEN can push
    steps:
      # 1) Check out full history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build your Vite app
      - name: Build
        run: npm run build

      # 5) Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          enable_jekyll: false
